### ISSUE TITLE
GHC.Types.BreakInfo not available with the required GHC version

### ISSUE THREAD

**Issue by zk453** [phoityne/ghci-dap#17]
Hello! I'm trying to install this but stack forces version 9.10.2 for ghc:

```stack install haskell-dap ghci-dap
ghc-paths  > using precompiled package
haskell-dap> using precompiled package
ghci-dap   > configure   
ghci-dap   > Configuring ghci-dap-0.0.25.0...
ghci-dap   > build with ghc-9.10.2
ghci-dap   > Preprocessing library for ghci-dap-0.0.25.0...
ghci-dap   > Building library for ghci-dap-0.0.25.0...
ghci-dap   > [1 of 2] Compiling GHCi.DAP
ghci-dap   > [2 of 2] Compiling Paths_ghci_dap
ghci-dap   > Preprocessing executable 'ghci-dap' for ghci-dap-0.0.25.0...
ghci-dap   > Building executable 'ghci-dap' for ghci-dap-0.0.25.0...
ghci-dap   > [ 1 of 14] Compiling GHCi.DAP.Constant
ghci-dap   > [ 2 of 14] Compiling GHCi.GhcApiCompat
ghci-dap   > /tmp/stack-e9b694785fb216a0/ghci-dap-0.0.25.0/app-ghc-9.10/GHCi/GhcApiCompat.hs:49:1: error: [GHC-61948]
ghci-dap   > [ 4 of 14] Compiling GHCi.UI.Exception
ghci-dap   >     Could not find module ‘GHC.Types.BreakInfo’.
ghci-dap   >     Perhaps you meant
ghci-dap   >       GHC.Types.GREInfo (from ghc-9.10.2)
ghci-dap   >       GHC.Types.HpcInfo (from ghc-9.10.2)
ghci-dap   >       GHC.Types.Id.Info (from ghc-9.10.2)
ghci-dap   >     Use -v to see a list of the files searched for.
ghci-dap   >    |     
ghci-dap   > 49 | import GHC.Types.BreakInfo
ghci-dap   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^
ghci-dap   >          
ghci-dap   > [ 5 of 14] Compiling GHCi.UI.Info
ghci-dap   > [ 7 of 14] Compiling GHCi.Util
ghci-dap   > [ 8 of 14] Compiling GHCi.Leak
ghci-dap   > [13 of 14] Compiling Paths_ghci_dap
Completed 3 action(s).

Error: [S-7282]
       Stack failed to execute the build plan.
       
       While executing the build plan, Stack encountered the error:
       
       [S-7011]
       While building package ghci-dap-0.0.25.0 (scroll up to its section to see the error) using:
       /home/jeff/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_w2MFVN35_3.12.1.0_ghc-9.10.2 --verbose=1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/ghc-9.10.2 build --ghc-options " -fdiagnostics-color=always"
       Process exited with code: ExitFailure 1 ```

When looking at the GHC package it has the required module at version 9.10.1: 

<img width="635" height="205" alt="Image" src="https://github.com/user-attachments/assets/d9019996-08fa-459f-8d4f-c431dbd156a6" />

but not at 9.10.2:

<img width="786" height="466" alt="Image" src="https://github.com/user-attachments/assets/095352f2-5c6b-4512-be7c-3b54e338b693" />
