### ISSUE TITLE
Does not compile on MacOS

### ISSUE THREAD

**Issue by mouse07410** [phoityne/ghci-dap#14]
- MacOS Sequoia 15.2, Xcode-16.2.
- Cabal-3.14.1.1
- GHC-9.4.8, 9.2.8

```text
$ cabal install ghci-dap --overwrite-policy=always -w ghc-9.4.8
Resolving dependencies...
Build profile: -w ghc-9.4.8 -O2
In order, the following will be built (use -v for more details):
 - ghci-dap-0.0.23.0 (exe:ghci-dap) (requires build)
Starting     ghci-dap-0.0.23.0 (exe:ghci-dap)
Building     ghci-dap-0.0.23.0 (exe:ghci-dap)

Failed to build exe:ghci-dap from ghci-dap-0.0.23.0.
Build log ( /Users/ur20980/.cabal/logs/ghc-9.4.8/ghc-dp-0.0.23.0-5bbbf3e1.log
):
Configuring executable 'ghci-dap' for ghci-dap-0.0.23.0...
Preprocessing executable 'ghci-dap' for ghci-dap-0.0.23.0...
Building executable 'ghci-dap' for ghci-dap-0.0.23.0...

on the commandline: warning: [-Wunrecognised-warning-flags]
    unrecognised warning flag: -Wno-x-partial
[1 of 6] Compiling GHCi.DAP.Constant ( app/GHCi/DAP/Constant.hs, dist/build/ghci-dap/ghci-dap-tmp/GHCi/DAP/Constant.dyn_o )
[2 of 6] Compiling GHCi.DAP.Type    ( app/GHCi/DAP/Type.hs, dist/build/ghci-dap/ghci-dap-tmp/GHCi/DAP/Type.dyn_o )

app/GHCi/DAP/Type.hs:10:1: error:
    Could not find module ‘GHCi.GhcApiCompat’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
10 | import qualified GHCi.GhcApiCompat as GAC
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[5 of 6] Compiling Paths_ghci_dap   ( dist/build/ghci-dap/autogen/Paths_ghci_dap.hs, dist/build/ghci-dap/ghci-dap-tmp/Paths_ghci_dap.dyn_o )
Error: [Cabal-7125]
Failed to build exe:ghci-dap from ghci-dap-0.0.23.0. See the build log above for details.

$ 
```

Interestingly, it seemed to compile fine with GHC-9.10.1  - so this problem is not a show-stopper. Still, GHC-9.4.8 is still the "recommended" version - so, it would be nice if `ghci-dap` could compile successfully under it.

**Comment by steve-anunknown** [comment]
Hey, just confirming that this is an issue for me too for ghc 9.4.8 and not just on Mac OS. I'm on ubuntu 24.04.

**Comment by phoityne** [comment]
Hi.
Try ghci-dap-0.0.25.0.
It supports GHC 9.4.

**Comment by steve-anunknown** [comment]
thanks @phoityne, `stack install haskell-debug-adapter ghci-dap-0.0.25.0 haskell-dap-0.0.16.0 hie-bios-0.14.0` this ended up working for me.
